services:
  app:
    image: manologcode/dxf_extrude
    build:
        context: .
        dockerfile: Dockerfile
    container_name: dxf_extrude
    command: python -m flask --debug run --host=0.0.0.0 --reload
    # command: gunicorn -w 4 -b 0.0.0.0:5000 "wsgi:app" 
    environment:
      - FLASK_APP=app.py
    ports: 
      - 5000:5000
    volumes:
      - ./app:/app
    networks:
      - app_network

networks:
  app_network:
 